DROP USER FINANCE CASCADE

SELECT * FROM ALL_USERS
WHERE USERNAME = 'EXCELLENCEAPP_USER'

SELECT * FROM DBA_USERS
WHERE USERNAME = 'EXCELLENCEAPP_USER'


-- CHANGE THE PASSWORD IN ORACLE
ALTER USER APPLICATION IDENTIFIED BY APPLICATION

-- HOW TO KILL SESSION IN ORACLE
SELECT * FROM V$SESSION
WHERE USERNAME IS NOT NULL

ALTER SYSTEM DISCONNECT SESSION 'sid,serial#' IMMEDIATE;

SELECT * FROM DBA_ROLES


-----------------APPLICATION USER-----------------
CREATE USER APPLICATION IDENTIFIED BY APPLICATION
GRANT CREATE SESSION,GRANT ANY PRIVILEGE TO APPLICATION
GRANT CONNECT, RESOURCE, DBA TO APPLICATION
GRANT CONNECT TO APPLICATION
GRANT SELECT ON APPLICATION.USERINFO TO FINANCE;
GRANT REFERENCES ON APPLICATION.USERINFO TO FINANCE;

-----------------FINANCE USER---------------------
CREATE USER FINANCE IDENTIFIED BY FINANCE
GRANT UNLIMITED TABLESPACE TO FINANCE
GRANT CREATE SESSION TO FINANCE
GRANT CREATE TABLE TO FINANCE